## Numpy Library Exercises

In [95]:
import numpy as np
import random as rd

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [5]:
import numpy as np

arr = np.random.randint(0, 11, size=10)
print("до:", arr)

mask = (arr > 3) & (arr < 8)
arr[mask] *= -1

print("после:", arr)

до: [2 7 2 2 3 5 0 6 1 9]
после: [ 2 -7  2  2  3 -5  0 -6  1  9]


**2.** Replace the maximum element of a random array with 0

In [ ]:
arr = np.random.randint(0, 11, size=4)
print('До: ', arr)

mask = arr == arr.max()
arr[mask] = 0
print('После: ', arr)

До:  [6 5 3 5]
[0 5 3 5]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [19]:
arr = np.array([[1, 2], [3, 4]])

x, y = np.meshgrid(arr[0], arr[1])
result = np.column_stack([x.ravel(), y.ravel()])
print(result)

[[1 3]
 [2 3]
 [1 4]
 [2 4]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [22]:
np.random.seed(42)
A = np.random.randint(0, 6, size=(8, 3))
B = np.random.randint(0, 6, size=(2, 2))

mask = np.all([np.isin(A, b).any(axis=1) for b in B], axis=0)
result = A[mask]

print("A:\n", A)
print("B:\n", B)
print("Результат:\n", result)



A:
 [[3 4 2]
 [4 4 1]
 [2 2 2]
 [4 3 2]
 [5 4 1]
 [3 5 5]
 [1 3 4]
 [0 3 1]]
B:
 [[5 4]
 [3 0]]
Результат:
 [[3 4 2]
 [4 3 2]
 [3 5 5]
 [1 3 4]]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [56]:
matrix = np.random.randint(0,3, size=(10,3))
print('Initial matrix: \n', matrix)
mask = (np.diff(matrix) == 0).all(axis=1)
result = matrix[~mask]
print('New: \n', result)


Initial matrix: 
 [[1 1 2]
 [1 1 0]
 [1 1 2]
 [2 2 2]
 [2 2 1]
 [2 2 0]
 [1 1 1]
 [2 2 2]
 [0 2 0]
 [1 2 0]]
New: 
 [[1 1 2]
 [1 1 0]
 [1 1 2]
 [2 2 1]
 [2 2 0]
 [0 2 0]
 [1 2 0]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [31]:
ar2 = np.random.randint(0,10, size = (10,2))
arr = np.array([[1, 2],
                [3, 4],
                [1, 2], 
                [5, 6]])

np.unique(arr, axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [3]:
X = np.random.randint(0,5,size=(4,3))
diag = np.diag(X)
print('Prod: ', np.prod(diag[diag != 0]))

Prod:  8


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [47]:
x = np.random.randint(0,5,size=4)
y = np.random.randint(0,5,size=4)
print(x,y)
print(np.array_equal(np.sort(x),np.sort(y)))

[0 0 1 3] [2 3 3 0]
False


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [59]:
x = np.random.randint(0,6,size=(rd.randint(10,15)))
print(x)

preceded_by_zero = x[1:][x[:-1] == 0]
result = np.max(preceded_by_zero) if len(preceded_by_zero) > 0 else None

print(result)  

[1 3 0 3 4 1 3 2 5 0 4 4]
4


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
x = np.random.randint(0,8,size=rd.randint(5,10))
print(x)
values, counts = np.unique(x, return_counts=True)
print((values,counts))

[7 6 3 3 1 2 4 1 7 3]
(array([1, 2, 3, 4, 6, 7]), array([2, 1, 3, 1, 1, 2]))


* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [ ]:
X = np.random.randint(0, 10, size=(5, 3))
Y = np.random.randint(0, 10, size=(5, 3))

print("X:\n", X)
print("Y:\n", Y)

# numpy
t0 = time.time()
diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
dist_np = np.sqrt((diff ** 2).sum(axis=2))
t1 = time.time()
print("NumPy:", t1 - t0)

# scipy
t0 = time.time()
dist_scipy = cdist(X, Y, metric='euclidean')
t1 = time.time()
print("SciPy:", t1 - t0)

# проверяем что результаты одинаковые
print("Результаты совпадают:", np.allclose(dist_np, dist_scipy))


X:
 [[3 6 3]
 [9 6 2]
 [7 2 7]
 [4 2 6]
 [4 2 1]]
Y:
 [[2 6 2]
 [3 3 3]
 [3 7 3]
 [6 2 6]
 [5 3 9]]
Матрица расстояний:
 [[1.41421356 3.         1.         5.83095189 7.        ]
 [7.         6.78232998 6.164414   6.40312424 8.60232527]
 [8.1240384  5.74456265 7.54983444 1.41421356 3.        ]
 [6.         3.31662479 5.91607978 2.         3.31662479]
 [4.58257569 2.44948974 5.47722558 5.38516481 8.1240384 ]]


_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [106]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [107]:
calorie_stats = np.loadtxt("/Users/lena/Desktop/Python-Tasks/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [108]:
average_calories = calorie_stats.mean()
print('Average Calories: ', average_calories)
print(f'On average, CrunchieMunchies has {average_calories-60} less calories than its competitors')

Average Calories:  106.88311688311688
On average, CrunchieMunchies has 46.883116883116884 less calories than its competitors


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [110]:
calorie_stats_sorted = np.sort(calorie_stats)

4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [111]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [112]:
n = 0
nth_percentile = 0
while nth_percentile <= 60:
    n+=1
    nth_percentile = np.percentile(calorie_stats_sorted, n)
    print(f'{n}th percentile: {nth_percentile}')
    
print(f'\nОтвет: {n}th percentile: {nth_percentile}')

1th percentile: 50.0
2th percentile: 50.0
3th percentile: 55.599999999999994
4th percentile: 70.0

Ответ: 4th percentile: 70.0


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [ ]:

more_calories = (calorie_stats_sorted > 60).sum() * 100 / len(calorie_stats_sorted)
print(more_calories)

96.1038961038961


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [ ]:
calorie_std = calorie_stats_sorted.std()
print(calorie_std)

19.35718533390827


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [130]:
crunchie_calories = 60

print(f"""

At just {crunchie_calories} calories per serving, CrunchieMunchies contains 
nearly half the calories of the average competitor, which clocks 
in at {average_calories:.1f} calories — a difference of {average_calories - crunchie_calories:.1f} calories per serving.

{more_calories:.1f}% of competing cereals exceed {crunchie_calories} calories, 
meaning CrunchieMunchies outperforms virtually the entire market.

The median calorie count among competitors sits at {median_calories:.0f} calories,
confirming that the high average is not skewed by outliers — 
most competing products genuinely contain around 
{median_calories / crunchie_calories:.0f}x the calories of CrunchieMunchies.

The standard deviation of {calorie_std:.1f} calories indicates a relatively 
tight distribution — the market is uniformly high-calorie, 
and CrunchieMunchies stands out as a clear exception.

RECOMMENDATION: Lead with the '{more_calories:.0f}% of cereals have more calories' 
stat — it's concrete, striking, and easy for consumers to understand.
The {average_calories - crunchie_calories:.0f}-calorie difference per serving adds up 
to {(average_calories - crunchie_calories) * 365:.0f} calories saved per year.
""")



At just 60 calories per serving, CrunchieMunchies contains 
nearly half the calories of the average competitor, which clocks 
in at 106.9 calories — a difference of 46.9 calories per serving.

96.1% of competing cereals exceed 60 calories, 
meaning CrunchieMunchies outperforms virtually the entire market.

The median calorie count among competitors sits at 110 calories,
confirming that the high average is not skewed by outliers — 
most competing products genuinely contain around 
2x the calories of CrunchieMunchies.

The standard deviation of 19.4 calories indicates a relatively 
tight distribution — the market is uniformly high-calorie, 
and CrunchieMunchies stands out as a clear exception.

RECOMMENDATION: Lead with the '96% of cereals have more calories' 
stat — it's concrete, striking, and easy for consumers to understand.
The 47-calorie difference per serving adds up 
to 17112 calories saved per year.

